INITIAL_YEAR = 2017
FINAL_YEAR = 2036
MAX_AGE = 100

AGE_RANGE = range(0, MAX_AGE)
YEARS = range(INITIAL_YEAR, FINAL_YEAR)

ESCENARIO = 1

NO_SENSIBILITY = 'NO_SENSIBILITY'
LIFE_SENSIBILITY = 'LIFE_SENSIBILITY'
TIME_SENSIBILITY = 'TIME_SENSIBILITY'
SAVING_SENSIBILITY = 'SAVING_SENSIBILITY'


SENSIBILITY = NO_SENSIBILITY
