INITIAL_YEAR = 2017
FINAL_YEAR = 2037
MAX_AGE = 100

AGE_RANGE = range(0, MAX_AGE)
YEARS = range(INITIAL_YEAR, FINAL_YEAR)

INTERVALS_LABELS = ['0-14', '15-29', '30-64', '65-100']

ESCENARIO = 1

NO_SENSIBILITY = 'NO_SENSIBILITY'
LIFE_SENSIBILITY = 'LIFE_SENSIBILITY'
TIME_SENSIBILITY = 'TIME_SENSIBILITY'
SAVING_SENSIBILITY = 'SAVING_SENSIBILITY'


SENSIBILITY = NO_SENSIBILITY
